HW2 is completed
zoolberc/otus-hw pull request #2
Opened 2023-06-25 08:32 UTC by zoolberc

Домашнее задание №2 «Распаковка строки»

Критерии оценки
Пайплайн зелёный - 4 балла
Добавлены новые юнит-тесты - до 4 баллов
Понятность и чистота кода - до 2 баллов
Дополнительное задание на баллы не влияет
Зачёт от 7 баллов

2023-06-26 18:06 UTC, dshemin requested changes

2023-06-26 18:06 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +		if err != nil {
Критично:

Надо упростить, слишком большая вложенность о чем и говорит линтер. Ниже опишу ряд вещей которые стоит сделать.

2023-06-26 18:06 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +					preValue = string(s)
Важно:

`preValue = string(s)` у нас в обоих ветках, можно сделать так:

```
if err != nil {
    result.WriteString(preValue)
}
preValue = string(s)
```

2023-06-26 18:06 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +			if err != nil {
Важно:

Инвертируйте условие, обработайте err == nil в теле верните ошибку и тогда можно обойтись без else

2023-06-26 18:06 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +	inputWordRune := []rune(inputWord)
Важно:

Посмотрите пожалуйста данный пример https://go.dev/play/p/VY9wRxx0lr при итерировании по строке мы будем получать руны

2023-06-26 18:06 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +				_, err := strconv.Atoi(preValue)
Важно:

В обоих ветках мы пытаемся преврать preValue в число, вынесите это вне условия

2023-06-26 18:06 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +			_, err := strconv.Atoi(preValue)
Важно:

Тут мы тоже конвертируем preValue в число, сделайте в одном мести и потом работайте с результатом.

2023-07-01 08:23 UTC, zoolberc commented on hw02_unpack_string/unpack.go
> +			if err != nil {
Исправил

2023-07-01 08:25 UTC, zoolberc commented on hw02_unpack_string/unpack.go
> +					preValue = string(s)
Исправил

2023-07-01 08:43 UTC, zoolberc commented on hw02_unpack_string/unpack.go
> +	inputWordRune := []rune(inputWord)
Исправил

2023-07-01 08:45 UTC, zoolberc commented on hw02_unpack_string/unpack.go
> +				_, err := strconv.Atoi(preValue)
Исправил

2023-07-01 08:47 UTC, zoolberc commented on hw02_unpack_string/unpack.go
> +			_, err := strconv.Atoi(preValue)
Исправил

2023-07-01 08:48 UTC, zoolberc commented on hw02_unpack_string/unpack.go
> +		if err != nil {
Все замечания ниже исправил

2023-07-01 18:29 UTC, dshemin approved these changes

2023-07-02 08:22 UTC, merged