HW3 completed
zoolberc/otus-hw pull request #3
Opened 2023-07-02 08:24 UTC by zoolberc

Критерии оценки

- Пайплайн зелёный - 4 балла
- Добавлены новые юнит-тесты - до 4 баллов
- Понятность и чистота кода - до 2 баллов
- Дополнительное задание на баллы не влияет

Зачёт от 7 баллов

2023-07-02 12:06 UTC, dshemin requested changes

2023-07-02 12:06 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +		_, ok := wordsMap[word]
Важно:

Можно просто wordsMap[word]++, посмотрите внимательно на свойства мапы.

2023-07-02 12:06 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +	tempSliceOfNotSortedWords := getSortedSliceFromMap(wordsMap)[:10]
Важно:

Результат функции `getSortedSliceFromMap` мы присваеваем переменной `tempSliceOfNotSortedWords`, в результате получаем следующее логическое высказывание, функция которая возвращает отсортированный слайс из мапы - на самом деле не отсортирован. Скорее всего неудачный нейминг.

2023-07-02 12:06 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +	for i, k := range tempSliceOfNotSortedWords {
Важно:

Крайне усложнили код, с первого захода непонятно что тут происходит. Надо было в функции sort.SliceStable просто указать все необходимые условия, т.е. сортировать по количеству и в лексико графическом порядке, потом вычислить сколько элементов нам надо вернуть (по заданию 10, но в предложении может быть только 4 уникальных слова). Далее использовать полученное количество элементов в операторе `[:computedLenOnPreviousStep]` над слайсом чтобы получить топ.

2023-07-08 15:24 UTC, zoolberc commented on hw03_frequency_analysis/top.go
> +		_, ok := wordsMap[word]
Исправил

2023-07-08 15:25 UTC, zoolberc commented on hw03_frequency_analysis/top.go
> +	tempSliceOfNotSortedWords := getSortedSliceFromMap(wordsMap)[:10]
Исправил

2023-07-16 12:38 UTC, dshemin approved these changes

2023-07-16 12:38 UTC, dshemin commented on hw01_hello_otus/main.go
> +	wordsMap := make(map[string]int)
Важно:

Видимо вы что-то тестировали и забыли вернуть назад.

2023-07-16 12:38 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +	counts := make([]int, 0, len(countToWordsMap))
Важно:

Попробую объяснить на более подробном примере. Запустите и разберите код ниже - он практически полное решении задачи:
```
package main

import (
	"fmt"
	"sort"
)

func main() {
	fmt.Printf("%#v\n", run())
}

func run() []string {
	words := []string{"foo", "bar", "fizz", "buzz"}
	wordCounts := map[string]int{
		"foo":  4,
		"bar":  1,
		"fizz": 3,
		"buzz": 3,
	}

	sort.Slice(words, func(i, j int) bool {
		if wordCounts[words[i]] == wordCounts[words[j]] {
			return words[i] < words[j]
		}
		return wordCounts[words[i]] < wordCounts[words[j]]
	})

	max := 10
	if l := len(words); l < max {
		max = l
	}
	return words[:max]
}
```

2023-07-22 15:50 UTC, dshemin approved these changes

2023-07-23 08:38 UTC, merged