HW4 completed
zoolberc/otus-hw pull request #4
Opened 2023-07-23 15:58 UTC by zoolberc

### Критерии оценки
- Пайплайн зелёный - 4 балла
- Добавлены новые юнит-тесты для списка - 1 балл
- Добавлены новые юнит-тесты для кэша (см. выше) - до 3 баллов
- Понятность и чистота кода - до 2 баллов
- Дополнительное задание на баллы не влияет

#### Зачёт от 7 баллов

2023-07-25 04:20 UTC, dshemin requested changes

2023-07-25 04:20 UTC, dshemin commented on hw04_lru_cache/list.go
> +	items map[*ListItem]struct{}
Важно:

Зачем тут это свойство?

2023-07-25 05:58 UTC, zoolberc commented on hw04_lru_cache/list.go
> +	items map[*ListItem]struct{}
Чтобы возвращать кол-во элементов в списке и при вызове метода смещения элемента в начало, понимать, есть ли такой элемент в нашем списке не пройдя по всему списку.

2023-08-23 15:16 UTC, zoolberc commented on hw04_lru_cache/list.go
> +	items map[*ListItem]struct{}
Использовал для определения существования элемента в списке.
Забыл про этот пункт в задании "Считаем, что методы Remove и MoveToFront вызываются только от существующих в списке элементов." 
Убрал использование мапы

2023-08-23 16:11 UTC, dshemin approved these changes

2023-08-23 18:32 UTC, merged